name: Check Releases Template

on:
  workflow_call:
    inputs:
      item-id:
        required: true
        type: string
      github-org:
        required: true
        type: string
      github-repo:
        required: true
        type: string
      tag:
        required: false
        default: false
        type: boolean
      latestRelease:
        required: false
        default: false
        type: boolean
      allReleases:
        required: false
        default: false
        type: boolean
      allReleasesMatch:
        required: false
        type: string

jobs:
  check-release:
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install
      working-directory: scripts

    - name: Run script
      working-directory: scripts
      run: |
        node github-release.js ${{ inputs.item-id }} ${{ inputs.github-org }} ${{ inputs.github-repo }} $GITHUB_TOKEN ${{ inputs.tag }} ${{ inputs.latestRelease }} ${{ inputs.allReleases }} ${{ inputs.allReleasesMatch }} 
        CHANGELOG_URL=$(node changelog-url.js ${{ inputs.item-id }})
        echo "CHANGELOG_URL=${CHANGELOG_URL}" >> "$GITHUB_ENV"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5.0.2
      with:
        title: "New ${{ inputs.item-id }} release"
        commit-message: "New ${{ inputs.item-id }} release"
        branch: "${{ inputs.item-id }}/new-release"
        add-paths: "items/*.json"
        reviewers: "${{ env.ASSIGNEE }}"
        body: ${{ env.CHANGELOG_URL }}