name: Check Releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at 12:00 AM UTC

jobs:
  bitcoin-core:
    uses: ./.github/workflows/check-release-template.yml
    with:
      item-id: bitcoin-core
      github-org: bitcoin
      github-repo: bitcoin
      latestRelease: true
  minibolt:
    uses: ./.github/workflows/check-release-template.yml
    with:
      item-id: minibolt
      github-org: minibolt-guide
      github-repo: minibolt
      latestRelease: true
  mynode-community-edition:
    uses: ./.github/workflows/check-changelog-template.yml
    with:
      item-id: mynode-community-edition
      changelog-url: https://raw.githubusercontent.com/mynodebtc/mynode/master/CHANGELOG
  mynode-model-one:
    uses: ./.github/workflows/check-changelog-template.yml
    with:
      item-id: mynode-model-one
      changelog-url: https://raw.githubusercontent.com/mynodebtc/mynode/master/CHANGELOG
  mynode-model-two:
    uses: ./.github/workflows/check-changelog-template.yml
    with:
      item-id: mynode-model-two
      changelog-url: https://raw.githubusercontent.com/mynodebtc/mynode/master/CHANGELOG
  mynode-premium:
    uses: ./.github/workflows/check-changelog-template.yml
    with:
      item-id: mynode-premium
      changelog-url: https://raw.githubusercontent.com/mynodebtc/mynode/master/CHANGELOG
  parmanode:
    uses: ./.github/workflows/check-changelog-template.yml
    with:
      item-id: parmanode
      changelog-url: https://raw.githubusercontent.com/ArmanTheParman/Parmanode/master/changelog
  raspiblitz:
    uses: ./.github/workflows/check-release-template.yml
    with:
      item-id: raspiblitz
      github-org: raspiblitz
      github-repo: raspiblitz
      latestRelease: true
  start9-diy:
    uses: ./.github/workflows/check-release-template.yml
    with:
      item-id: start9-diy
      github-org: Start9Labs
      github-repo: start-os
      latestRelease: true
  start9-server-one:
    uses: ./.github/workflows/check-release-template.yml
    with:
      item-id: start9-server-one
      github-org: Start9Labs
      github-repo: start-os
      latestRelease: true
  start9-server-pure:
    uses: ./.github/workflows/check-release-template.yml
    with:
      item-id: start9-server-pure
      github-org: Start9Labs
      github-repo: start-os
      latestRelease: true
  umbrel-diy:
    uses: ./.github/workflows/check-release-template.yml
    with:
      item-id: umbrel-diy
      github-org: getumbrel
      github-repo: umbrel
      latestRelease: true
  umbrel-home:
    uses: ./.github/workflows/check-release-template.yml
    with:
      item-id: umbrel-home
      github-org: getumbrel
      github-repo: umbrel
      latestRelease: true
  